### PR TITLE
update

### PR DESCRIPTION
**Pull request by QWERTY770**

### CODE REVIEW

**Comment by teddyxlandlee** [comment]
So much for the update.

I'm gonna check it later.

Since TeaCon 2022 has been over, is it necessary to keep such a "stable/compilable" `master` branch?

**Comment by teddyxlandlee** [comment]
Wait, this is…actually the earlier multiplatform `trunk` without new things.

Since there's nothing in my workspace, I'm gonna merge it.

**Comment by teddyxlandlee** [comment]
Wait…there's still some conflicts. Could you please recheck it?

**Comment by QWERTY770** [comment]
> Wait…there's still some conflicts. Could you please recheck it?

I added some new blocks today. However, I forgot to merge the commits from Xdi8Mod/Xdi8aho-Mod before that. 

There are three conflicts but I really have no idea how to resolve them.

**Comment by QWERTY770** [comment]
The conflicts are resolved successfully!

**Pull request merged**
